
pipeline {
    agent any
    
    stages {
        stage('compile stage') {
            steps {
                withMaven (maven: 'apache-maven-3.0.5') {
                 sh 'mvn clean compile'
            
                }
                
                
                stage('test stage') {
            steps {
                withMaven (maven: 'apache-maven-3.0.5') {
                 sh 'mvn test'
                 }
                 
                 stage('Deploy') {
            steps {
                withMaven (maven: 'apache-maven-3.0.5') {
                 sh 'mvn deploy'
                 }
                
          
            }
        }
    }
}